language: "es"  # Idioma del chatbot (español)

pipeline:  # Definición del pipeline de NLU
  - name: WhitespaceTokenizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: LanguageModelTokenizer
    model_name: "dccuchile/bert-base-spanish-wwm-cased"  # Nombre del modelo BERT en español
    model_weights: "dccuchile/bert-base-spanish-wwm-cased" #usar uncased
    #cache_dir: "path_to_bert_cache_directory"  # Opcional, si deseas especificar una carpeta de caché

  # Otros componentes de procesamiento de lenguaje natural
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100

policies:  # Definición de políticas de manejo de conversación
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: RulePolicy
